#NAME: Arpit Jasapara
#EMAIL: ajasapara@ucla.edu
#ID: XXXXXXXXX

.SILENT:

default:
	gcc -Wall -Wextra -g -o lab3a lab3a.c -lm
clean:
	rm -f lab3a-XXXXXXXXX.tar.gz lab3a
dist:
	tar -czf lab3a-XXXXXXXXX.tar.gz README Makefile lab3a.c ext2_fs.h