#NAME: Arpit Jasapara
#EMAIL: ajasapara@ucla.edu
#ID: XXXXXXXXX

.SILENT:

default: 
	gcc -Wall -Wextra -o lab1a lab1a.c
clean:
	rm -f lab1a lab1a-504742401.tar.gz
dist:
	tar -czf lab1a-504742401.tar.gz lab1a.c Makefile README