#NAME: Arpit Jasapara
#EMAIL: ajasapara@ucla.edu
#ID: XXXXXXXXX

.SILENT:

default:
	cp lab3b.py lab3b
	chmod +x lab3b lab3b.py
clean:
	rm -f lab3b-XXXXXXXXX.tar.gz lab3b
dist:
	tar -czf lab3b-XXXXXXXXX.tar.gz README Makefile lab3b.py