#NAME: Arpit Jasapara
#EMAIL: ajasapara@ucla.edu
#ID: XXXXXXXXX

.SILENT:

clean:
	rm -f lab4a-XXXXXXXXX.tar.gz
dist:
	tar -czf lab4a-XXXXXXXXX.tar.gz README connected.png copy.png build_run.png git.png my_beaglebone.jpg